<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-P4JKDR6" failures="0" tests="3" name="groupTests.NewTestAlwayasRun" time="1.029" errors="1" timestamp="2025-01-25T00:36:06 IST" skipped="0">
  <testcase classname="groupTests.NewTestAlwayasRun" name="test" time="0.001"/>
  <testcase classname="groupTests.NewTestAlwayasRun" name="testmethod2" time="1.022">
    <error message="Method groupTests.NewTestAlwayasRun.testmethod2() didn&#039;t finish within the time-out 1000" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method groupTests.NewTestAlwayasRun.testmethod2() didn't finish within the time-out 1000
at java.base/java.lang.Thread.sleep0(Native Method)
at java.base/java.lang.Thread.sleep(Thread.java:509)
at groupTests.NewTestAlwayasRun.testmethod2(NewTestAlwayasRun.java:29)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </error>
  </testcase> <!-- testmethod2 -->
  <testcase classname="groupTests.NewTestAlwayasRun" name="testMethod1" time="0.006"/>
</testsuite> <!-- groupTests.NewTestAlwayasRun -->
